### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by SharonRenwick** [steeren/wp-mattiana#4]
Is it me or is the gallery image very big?   Do I need to get you smaller one or can you shrink them?

Maybe its my laptop?

**Comment by steeren** [comment]
The images sizes need some how to be standardised. I would make all images 1024 * 768. That said, I will try to look a little further into the settings here and see if there is a way to enforce a fixed size, so bigger images are reduced to fit the area. This however would mean if you had images that were very small, they would be stretched to fit 1024 * 768 and this would look terrible. 

So I will leave this ticket open with the view that this needs to be standardised on my side some what. But you will also ensure that all "Gallery Photos" are uploaded to a standardised size (and quality).

**Comment by SharonRenwick** [comment]
Ok,  so basically going forward once we've established what size they need
to be keep them at that size

**Comment by steeren** [comment]
yup
