### ISSUE TITLE
Homepage 

### ISSUE THREAD

**Issue by SharonRenwick** [steeren/wp-mattiana#5]
I can't figure out how to attached my image??  Anyway will email it to you.  I hope I haven't made it to small for the textbox to across the bottom

**Comment by steeren** [comment]
No need to mail it to me. Upload it to the media section of WP. When its uploaded and you are viewing that image, you should see on the right side shows the URL for the image. Copy that and go to the Home Page. In the Home Page you should find down low in that page a "custom fields" section, update the "image" custom field with the new URL (you'll see the old one is there).

**Comment by SharonRenwick** [comment]
Ah I already have, I'll try doing it that way now if you like?

**Comment by steeren** [comment]
looks like you got it, home page images appear to be present and accounted for.
