### ISSUE TITLE
Overall Background image

### ISSUE THREAD

**Issue by SharonRenwick** [steeren/wp-mattiana#6]
Is it me or is it huge!  It looks very zoomed-in or something?  Is there anyway of making it smaller?

**Comment by steeren** [comment]
Yea, I said that to you. The image is massive, so you are only seeing a small part of it. I would STRONGLY recommend a smaller image (I'm actually not sure what they recommend - ask google). But a smaller image (smaller in pixel size and kilobytes). We have performance issues that I need to get fixed, one of performance issues is the large background image. If we can't get it right, I will push for no background image and just a colour, to me this would be far better.

**Comment by SharonRenwick** [comment]
Ah ok, will try and shrink image or just change it for a solid colour leave
that with me!

Yea, I said that to you. The image is massive, so you are only seeing a
small part of it. I would STRONGLY recommend a smaller image (I'm actually
not sure what they recommend - ask google). But a smaller image (smaller in
pixel size and kilobytes). We have performance issues that I need to get
fixed, one of performance issues is the large background image. If we can't
get it right, I will push for no background image and just a colour, to me
this would be far better.

—
Reply to this email directly or view it on GitHub
<https://github.com/steeren/wp-mattiana/issues/6#issuecomment-188959921>.
