### ISSUE TITLE
Testimonial page

### ISSUE THREAD

**Issue by SharonRenwick** [steeren/wp-mattiana#7]
Could you put customers name at the bottom of the page?   And also are you able to use the images I sent or do you need me to resend them?   I think I sent some?!

Also I notice grammatical errors, can I change them or do you need to at this stage?

**Comment by steeren** [comment]
One sec. Remember this is not the live site. Grammatical errors, typo's or spelling is your responsibility. So too are the photos. Look at "posts", they have the testimonials where things can be corrected.

**Comment by SharonRenwick** [comment]
Yes I'm only starting to get that I can change things too from your earlier
emails today.  Before you spoke I got the impress I need to wait for you to
finish before I could do anything.  I'll log on the wordpress and get
crackin!
